name: Push Maven Central Publication

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.commits[0].message, '[pub]')"
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set outputs
        id: vars
        run: |
          echo "short_commit_hash=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT

      - name: Publish to Sonatype
        env:
          CORE_VERSION: ${{ steps.vars.outputs.short_commit_hash }}
        run: |
          ./gradlew publishToCentralPortal
          echo "Version: ${SHORT_COMMIT_HASH}" >> $GITHUB_STEP_SUMMARY